name: Deploy INTER to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Deploy inter folder to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-kr-pdm-ea-prod-002'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: inter/.
